version: '3.8'
services:
  ec2-observability:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Add environment variables here if needed
      NODE_ENV: production
    restart: unless-stopped
