version: '3.8'
services:
  ec2-observability:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      BASE_URL: http://localhost:3000
      API_URL: http://localhost:3000/api
    restart: unless-stopped
